-- Seed data for laptops table
-- 100 records with statuses: 'new' (available), 'old' (available), 'needs_repair'
-- Columns: brand, model, condition, status, created_at
INSERT INTO laptops (brand, model, condition, status, created_at) VALUES
('Dell', 'XPS 13', 'new', 'available', NOW()),
('Apple', 'MacBook Air', 'new', 'available', NOW()),
('Lenovo', 'ThinkPad X1 Carbon', 'new', 'available', NOW()),
('HP', 'Spectre x360', 'new', 'available', NOW()),
('Asus', 'ZenBook 14', 'new', 'available', NOW()),
('Acer', 'Swift 3', 'new', 'available', NOW()),
('Microsoft', 'Surface Laptop 4', 'new', 'available', NOW()),
('Razer', 'Blade Stealth 13', 'new', 'available', NOW()),
('Samsung', 'Galaxy Book Pro', 'new', 'available', NOW()),
('LG', 'Gram 16', 'new', 'available', NOW()),
('Dell', 'Inspiron 15', 'old', 'available', NOW()),
('Apple', 'MacBook Pro 13', 'old', 'available', NOW()),
('Lenovo', 'IdeaPad 3', 'old', 'available', NOW()),
('HP', 'Pavilion 14', 'old', 'available', NOW()),
('Asus', 'VivoBook S15', 'old', 'available', NOW()),
('Acer', 'Aspire 5', 'old', 'available', NOW()),
('Microsoft', 'Surface Pro 7', 'old', 'available', NOW()),
('Razer', 'Blade 15', 'old', 'available', NOW()),
('Samsung', 'Notebook 9', 'old', 'available', NOW()),
('LG', 'Gram 14', 'old', 'available', NOW()),
('Dell', 'Latitude 7420', 'needs_repair', 'needs_repair', NOW()),
('Apple', 'MacBook Air (2017)', 'needs_repair', 'needs_repair', NOW()),
('Lenovo', 'ThinkPad T14', 'needs_repair', 'needs_repair', NOW()),
('HP', 'EliteBook 840', 'needs_repair', 'needs_repair', NOW()),
('Asus', 'ROG Zephyrus G14', 'needs_repair', 'needs_repair', NOW()),
('Acer', 'Predator Helios 300', 'needs_repair', 'needs_repair', NOW()),
('Microsoft', 'Surface Book 3', 'needs_repair', 'needs_repair', NOW()),
('Razer', 'Blade Pro 17', 'needs_repair', 'needs_repair', NOW()),
('Samsung', 'Galaxy Book Flex', 'needs_repair', 'needs_repair', NOW()),
('LG', 'Gram 17', 'needs_repair', 'needs_repair', NOW()),
('Dell', 'G5 15', 'new', 'available', NOW()),
('Apple', 'MacBook Pro 16', 'new', 'available', NOW()),
('Lenovo', 'Legion 5', 'new', 'available', NOW()),
('HP', 'Omen 15', 'new', 'available', NOW()),
('Asus', 'TUF Gaming A15', 'new', 'available', NOW()),
('Acer', 'Nitro 5', 'new', 'available', NOW()),
('Microsoft', 'Surface Go 2', 'new', 'available', NOW()),
('Razer', 'Blade 14', 'new', 'available', NOW()),
('Samsung', 'Galaxy Book Ion', 'new', 'available', NOW()),
('LG', 'Gram 15', 'new', 'available', NOW()),
('Dell', 'Precision 5550', 'old', 'available', NOW()),
('Apple', 'MacBook Pro (2020)', 'old', 'available', NOW()),
('Lenovo', 'ThinkPad L13', 'old', 'available', NOW()),
('HP', 'ProBook 450', 'old', 'available', NOW()),
('Asus', 'ZenBook Pro Duo', 'old', 'available', NOW()),
('Acer', 'Spin 5', 'old', 'available', NOW()),
('Microsoft', 'Surface Laptop Go', 'old', 'available', NOW()),
('Razer', 'Blade Stealth 13', 'old', 'available', NOW()),
('Samsung', 'Notebook 7', 'old', 'available', NOW()),
('LG', 'Gram 13', 'old', 'available', NOW()),
('Dell', 'XPS 15', 'needs_repair', 'needs_repair', NOW()),
('Apple', 'MacBook Pro (2019)', 'needs_repair', 'needs_repair', NOW()),
('Lenovo', 'ThinkPad X1 Yoga', 'needs_repair', 'needs_repair', NOW()),
('HP', 'Envy 13', 'needs_repair', 'needs_repair', NOW()),
('Asus', 'ROG Strix G15', 'needs_repair', 'needs_repair', NOW()),
('Acer', 'ConceptD 7', 'needs_repair', 'needs_repair', NOW()),
('Microsoft', 'Surface Pro X', 'needs_repair', 'needs_repair', NOW()),
('Razer', 'Blade 15 Advanced', 'needs_repair', 'needs_repair', NOW()),
('Samsung', 'Galaxy Book Pro 360', 'needs_repair', 'needs_repair', NOW()),
('LG', 'Gram 14', 'needs_repair', 'needs_repair', NOW()),
('Dell', 'Vostro 15', 'new', 'available', NOW()),
('Apple', 'MacBook Air M1', 'new', 'available', NOW()),
('Lenovo', 'IdeaPad Flex 5', 'new', 'available', NOW()),
('HP', 'Stream 11', 'new', 'available', NOW()),
('Asus', 'E410MA', 'new', 'available', NOW()),
('Acer', 'Swift 5', 'new', 'available', NOW()),
('Microsoft', 'Surface Laptop 3', 'new', 'available', NOW()),
('Razer', 'Blade Stealth 13', 'new', 'available', NOW()),
('Samsung', 'Galaxy Book Go', 'new', 'available', NOW()),
('LG', 'Gram 15', 'new', 'available', NOW()),
('Dell', 'Inspiron 14', 'old', 'available', NOW()),
('Apple', 'MacBook Pro 13 (2020)', 'old', 'available', NOW()),
('Lenovo', 'ThinkPad E15', 'old', 'available', NOW()),
('HP', 'Pavilion x360', 'old', 'available', NOW()),
('Asus', 'VivoBook Flip 14', 'old', 'available', NOW()),
('Acer', 'Aspire 7', 'old', 'available', NOW()),
('Microsoft', 'Surface Go', 'old', 'available', NOW()),
('Razer', 'Blade 15', 'old', 'available', NOW()),
('Samsung', 'Notebook 9 Pro', 'old', 'available', NOW()),
('LG', 'Gram 13', 'old', 'available', NOW()),
('Dell', 'Latitude 5420', 'needs_repair', 'needs_repair', NOW()),
('Apple', 'MacBook Air (2020)', 'needs_repair', 'needs_repair', NOW()),
('Lenovo', 'ThinkPad X13', 'needs_repair', 'needs_repair', NOW()),
('HP', 'EliteBook 850', 'needs_repair', 'needs_repair', NOW()),
('Asus', 'ROG Zephyrus G15', 'needs_repair', 'needs_repair', NOW()),
('Acer', 'Predator Triton 500', 'needs_repair', 'needs_repair', NOW()),
('Microsoft', 'Surface Laptop Studio', 'needs_repair', 'needs_repair', NOW()),
('Razer', 'Blade 14', 'needs_repair', 'needs_repair', NOW()),
('Samsung', 'Galaxy Book Pro 360', 'needs_repair', 'needs_repair', NOW()),
('LG', 'Gram 16', 'needs_repair', 'needs_repair', NOW()),
('Dell', 'G7 15', 'new', 'available', NOW()),
('Apple', 'MacBook Pro 14', 'new', 'available', NOW()),
('Lenovo', 'Legion 7', 'new', 'available', NOW()),
('HP', 'Omen 17', 'new', 'available', NOW()),
('Asus', 'TUF Gaming F15', 'new', 'available', NOW()),
('Acer', 'Nitro 7', 'new', 'available', NOW()),
('Microsoft', 'Surface Pro 8', 'new', 'available', NOW()),
('Razer', 'Blade 15', 'new', 'available', NOW()),
('Samsung', 'Galaxy Book Pro 360', 'new', 'available', NOW()),
('LG', 'Gram 15', 'new', 'available', NOW()),
('Dell', 'Precision 5560', 'old', 'available', NOW()),
('Apple', 'MacBook Pro (M1)', 'old', 'available', NOW()),
('Lenovo', 'ThinkPad X1 Extreme', 'old', 'available', NOW()),
('HP', 'ZBook Firefly', 'old', 'available', NOW()),
('Asus', 'ZenBook Pro Duo', 'old', 'available', NOW()),
('Acer', 'Spin 7', 'old', 'available', NOW()),
('Microsoft', 'Surface Laptop Studio', 'old', 'available', NOW()),
('Razer', 'Blade Pro 17', 'old', 'available', NOW()),
('Samsung', 'Galaxy Book Pro 360', 'old', 'available', NOW()),
('LG', 'Gram 16', 'old', 'available', NOW()),
('Dell', 'XPS 13', 'needs_repair', 'needs_repair', NOW()),
('Apple', 'MacBook Air (M2)', 'needs_repair', 'needs_repair', NOW()),
('Lenovo', 'ThinkPad X1 Nano', 'needs_repair', 'needs_repair', NOW()),
('HP', 'EliteBook 845', 'needs_repair', 'needs_repair', NOW()),
('Asus', 'ROG Flow X13', 'needs_repair', 'needs_repair', NOW()),
('Acer', 'ConceptD 3', 'needs_repair', 'needs_repair', NOW()),
('Microsoft', 'Surface Pro 9', 'needs_repair', 'needs_repair', NOW()),
('Razer', 'Blade 14', 'needs_repair', 'needs_repair', NOW()),
('Samsung', 'Galaxy Book Pro 360', 'needs_repair', 'needs_repair', NOW()),
('LG', 'Gram 15', 'needs_repair', 'needs_repair', NOW());
-- End of seed data
